apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend
spec:
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
      - name: flask-backend
        image: docker.io/roohinaks/assign-backend
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-backend
spec:
  selector:
    app: flask-backend
  ports:
  - port: 80
    targetPort: 8000
        
